### ISSUE TITLE
Unified plagiarism analysis

### ISSUE THREAD

**Issue by tcibinan** [gitplag/gitplag#3]
Gitplag supports two plagiarism analysis *backends* or *analysers* - `MOSS` and `JPlag`. They act differently in different circumstances so in some cases one of the backends is more appropriate then other. Nevertheless in most cases both backends perform pretty the same.

As long as Gitplag provides a backend-agnostic interface then it doesn't really matter what backend is used. As the [scientific paper](https://www.researchgate.net/publication/319402218_A_Unified_Approach_to_Automate_the_Usage_of_Plagiarism_Detection_Tools_in_Programming_Courses) suggests the consolidation of the several plagiarism backends can lead to an improving of an overall analysis quality.

Therefore, I suggest a creation of a third plagiarism analysis backend that uses both `MOSS` and `JPlag` to analyse submissions and consolidate their outputs.

**Comment by nikita715** [comment]
Thanks for the issue! I've added this feature in the latest release, but it will probably require some improvements in the future.

**Comment by tcibinan** [comment]
Looks fine by now, thanks!
